# Generated by Django 6.0.4 on 2026-04-19 10:32

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('city_name', models.CharField(db_index=True, default='Nashik', max_length=64)),
                ('zone_name', models.CharField(max_length=128)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('dispatch_radius_km', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
            ],
            options={
                'indexes': [models.Index(fields=['city_name', 'active'], name='service_zon_city_na_0ff5be_idx')],
                'unique_together': {('city_name', 'zone_name')},
            },
        ),
    ]
