# Generated by Django 6.0.4 on 2026-04-19 10:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('city', models.CharField(db_index=True, default='Nashik', max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('base_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_min_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minimum_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('night_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cancellation_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='vehicle_categories.vehiclecategory')),
            ],
            options={
                'indexes': [models.Index(fields=['city', 'active', 'starts_at'], name='pricing_pri_city_49aa93_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('surge_multiplier__gte', 1)), name='pricing_surge_gte_one'), models.CheckConstraint(condition=models.Q(('base_fare__gte', 0)), name='pricing_base_fare_gte_zero')],
            },
        ),
    ]
