# Generated by Django 6.0.4 on 2026-04-19 10:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicle_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('registration_number', models.CharField(db_index=True, max_length=32)),
                ('brand', models.CharField(blank=True, max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('manufacture_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], db_index=True, default='active', max_length=16)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicle_categories.vehiclecategory')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='drivers.driverprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('registration_number',), name='uniq_active_vehicle_registration')],
            },
        ),
    ]
