# Generated by Django 6.0.4 on 2026-04-19 10:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('icon', models.CharField(blank=True, max_length=128)),
                ('payload_type', models.CharField(max_length=64)),
                ('max_weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_volume_m3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_km_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waiting_per_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minimum_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('helper_supported', models.BooleanField(default=False)),
                ('intra_city_available', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('priority_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['priority_order', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='uniq_active_vehicle_category_name')],
            },
        ),
    ]
