# Generated by Django 6.0.4 on 2026-04-19 10:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rule_type', models.CharField(choices=[('extra_stop', 'Extra Stop'), ('helper', 'Helper'), ('tax', 'Tax'), ('coupon', 'Coupon'), ('waiting', 'Waiting')], db_index=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('pricing_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_rules', to='pricing.pricingrule')),
            ],
            options={
                'indexes': [models.Index(fields=['rule_type', 'active'], name='fare_rules__rule_ty_eff2af_idx')],
            },
        ),
    ]
