# Generated by Django 6.0.4 on 2026-04-19 10:32

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLiveLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('heading', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('speed_kmph', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('accuracy_m', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('source_timestamp', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_location_updates', to='bookings.booking')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_location', to='drivers.driverprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='tracking_dr_created_83fa98_idx'), models.Index(fields=['booking', 'created_at'], name='tracking_dr_booking_763950_idx')],
            },
        ),
    ]
