# Generated by Django 6.0.4 on 2026-04-19 10:32

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('service_zones', '0001_initial'),
        ('vehicle_categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('booking_type', models.CharField(choices=[('instant', 'Instant'), ('scheduled', 'Scheduled')], default='instant', max_length=32)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('pending_quote', 'Pending Quote'), ('searching_driver', 'Searching Driver'), ('driver_assigned', 'Driver Assigned'), ('driver_accepted', 'Driver Accepted'), ('driver_arriving', 'Driver Arriving'), ('driver_arrived', 'Driver Arrived'), ('pickup_otp_pending', 'Pickup OTP Pending'), ('trip_started', 'Trip Started'), ('in_transit', 'In Transit'), ('nearing_drop', 'Nearing Drop'), ('completed', 'Completed'), ('cancelled_by_customer', 'Cancelled By Customer'), ('cancelled_by_driver', 'Cancelled By Driver'), ('cancelled_by_admin', 'Cancelled By Admin'), ('payment_pending', 'Payment Pending'), ('refunded', 'Refunded'), ('failed', 'Failed')], db_index=True, default='draft', max_length=64)),
                ('pickup_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('drop_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('pickup_address_text', models.CharField(blank=True, max_length=255)),
                ('drop_address_text', models.CharField(blank=True, max_length=255)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('estimated_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_duration_min', models.PositiveIntegerField(default=0)),
                ('pricing_breakdown', models.JSONField(blank=True, default=dict)),
                ('estimated_fare', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('final_fare', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('cancellation_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('requires_helper', models.BooleanField(default=False)),
                ('otp_code', models.CharField(blank=True, max_length=8)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_bookings', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='drivers.driverprofile')),
                ('service_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_zones.servicezone')),
                ('vehicle_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle_categories.vehiclecategory')),
            ],
        ),
        migrations.CreateModel(
            name='BookingStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sequence', models.PositiveIntegerField()),
                ('stop_type', models.CharField(choices=[('pickup', 'Pickup'), ('waypoint', 'Waypoint'), ('drop', 'Drop')], db_index=True, max_length=16)),
                ('address_text', models.CharField(blank=True, max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='bookings.booking')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['state', 'created_at'], name='bookings_bo_state_739c39_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_type', 'scheduled_at'], name='bookings_bo_booking_693c25_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'created_at'], name='bookings_bo_custome_f17938_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_fare__gte', 0)), name='booking_estimated_fare_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('final_fare__gte', 0)), name='booking_final_fare_gte_zero'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingstop',
            unique_together={('booking', 'sequence')},
        ),
    ]
