# Generated by Django 6.0.4 on 2026-04-19 10:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('from_state', models.CharField(blank=True, max_length=64)),
                ('to_state', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('actor_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driverprofile')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_events', to='bookings.booking')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
                'indexes': [models.Index(fields=['booking', 'event_type', 'created_at'], name='trip_events_booking_68f9f7_idx')],
                'unique_together': {('booking', 'sequence')},
            },
        ),
    ]
