# Generated by Django 6.0.4 on 2026-04-19 10:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('trip_earning', 'Trip Earning'), ('bonus', 'Bonus'), ('incentive', 'Incentive'), ('penalty', 'Penalty'), ('manual_credit', 'Manual Credit'), ('manual_debit', 'Manual Debit'), ('payout_request', 'Payout Request'), ('payout_processed', 'Payout Processed'), ('payout_reversed', 'Payout Reversed'), ('refund_adjustment', 'Refund Adjustment')], db_index=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference_id', models.CharField(max_length=128, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'indexes': [models.Index(fields=['wallet', 'created_at'], name='wallet_tran_wallet__485323_idx'), models.Index(fields=['transaction_type', 'created_at'], name='wallet_tran_transac_95c707_idx'), models.Index(fields=['reference_id'], name='wallet_tran_referen_c75cd7_idx')],
            },
        ),
    ]
