# Generated by Django 6.0.4 on 2026-04-19 10:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('is_flagged', models.BooleanField(db_index=True, default=False)),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='ratings.rating')),
            ],
            options={
                'indexes': [models.Index(fields=['is_flagged', 'created_at'], name='reviews_rev_is_flag_196108_idx')],
            },
        ),
    ]
